### ISSUE TITLE
"List index out of range" from input_schema

### ISSUE THREAD

**Issue by byronverz** [Azure/InferenceSchema#34]
When defining an input schema using ``StandardPythonParameterType``, I get a ``list index out of range`` error.

I have the service deployed to my local machine and have ensured the service works without the schema decorators. Oddly though, the functionality is as expected when decorating a function within my notebook, it only fails on the deployed service.

The example I used:
```
standard_sample_input = {'name': ['Sarah', 'John'], 'age': [25, 26]}
standard_sample_output = {'age': [25, 26]}


@input_schema('param', StandardPythonParameterType(standard_sample_input))
@output_schema(StandardPythonParameterType(standard_sample_output))
def standard_py_func(param):
    assert type(param) is dict
    return {'age': param['age']}
```

**Comment by joshidp** [comment]
What was the solution provided for this issue? I'm also facing the same issue, please provide a solution

```
2021-06-30T03:05:58.099463444Z 2021-06-30 03:05:58,099 | root | INFO | Validation Request Content-Type
2021-06-30T03:05:58.100660957Z 2021-06-30 03:05:58,100 | root | ERROR | Encountered Exception: Traceback (most recent call last):
2021-06-30T03:05:58.100676557Z   File "/var/azureml-server/synchronous/routes.py", line 64, in run_scoring
2021-06-30T03:05:58.100692557Z     response = invoke_user_with_timer(service_input, request_headers)
2021-06-30T03:05:58.100746457Z   File "/var/azureml-server/synchronous/routes.py", line 89, in invoke_user_with_timer
2021-06-30T03:05:58.100766958Z     params = prepare_user_params(input, headers, aml_request._rawHttpRequested)
2021-06-30T03:05:58.100770458Z   File "/var/azureml-server/routes_common.py", line 141, in prepare_user_params
2021-06-30T03:05:58.100773858Z     params = {main.run_input_parameter_name: input[main.wrapped_parameter_name]}
2021-06-30T03:05:58.100777158Z TypeError: list indices must be integers or slices, not str
2021-06-30T03:05:58.100780458Z
2021-06-30T03:05:58.100783658Z During handling of the above exception, another exception occurred:
2021-06-30T03:05:58.100786958Z
2021-06-30T03:05:58.100790058Z Traceback (most recent call last):
2021-06-30T03:05:58.100793458Z   File "/azureml-envs/azureml_a8297c74e6ecce9cd47fcb8669ec1e61/lib/python3.8/site-packages/flask/app.py", line 1832, in full_dispatch_request
2021-06-30T03:05:58.100797158Z     rv = self.dispatch_request()
2021-06-30T03:05:58.100800358Z   File "/azureml-envs/azureml_a8297c74e6ecce9cd47fcb8669ec1e61/lib/python3.8/site-packages/flask/app.py", line 1818, in dispatch_request
2021-06-30T03:05:58.100803858Z     return self.view_functions[rule.endpoint](**req.view_args)
2021-06-30T03:05:58.100807158Z   File "/var/azureml-server/synchronous/routes.py", line 43, in score_realtime
2021-06-30T03:05:58.100810658Z     return run_scoring(service_input, request.headers, request.environ.get('REQUEST_ID', '00000000-0000-0000-0000-000000000000'))
2021-06-30T03:05:58.100814058Z   File "/var/azureml-server/synchronous/routes.py", line 77, in run_scoring
2021-06-30T03:05:58.100819058Z     raise RunFunctionException(str(exc))
2021-06-30T03:05:58.100822358Z run_function_exception.RunFunctionException
```

**Comment by byronverz** [comment]
@joshidp Microsoft didn't provide me any solution, but I found that using the PandasParameterType for everything did help. I still think this should be addressed but Microsoft took too long to reply
